language: dart
dart:
  - dev

# Build stages: https://docs.travis-ci.com/user/build-stages/.
stages:
  - analyze_and_format
  - testing
  - prepub
  - deploy

jobs:
  include:
    - stage: analyze_and_format
      name: "Analysing and checking formating"
      script: ./tool/travis/swag.sh

    - stage: testing
      name: "Unit testing"
      script: pub run test
    
    - stage: prepub
      name: "Checking predeploy on pub (dry-run)"
      script: pub publish --dry-run

    - stage: deploy
      name: "Deploying on pub.dartlang.org"
      deploy:
        provider: script
        script: ./tool/travis/pub.sh
        on:
          branch: master

branches:
  only: [master, /feature\..*/]

# Incremental pub cache and builds.
cache:
  directories:
    - $HOME/.pub-cache
